### ISSUE TITLE
Lighter dependencies?

### ISSUE THREAD

**Issue by fregante** [maikelvl/dot-json#14]
I noticed that dot-json has relatively large dependencies (the whole underscore) that _could_ be replaced with smaller alternatives.

- [sade](https://packagephobia.com/result?p=sade) instead of [docopt](https://packagephobia.com/result?p=docopt)
- [dot-prop](https://packagephobia.com/result?p=dot-prop) instead of [underscore-keypath](https://packagephobia.com/result?p=underscore-keypath) (once https://github.com/sindresorhus/dot-prop/issues/71 is solved)

One thing to be aware of is that `dot-prop` is not equivalent, but the advanced features of `underscore-keypath` were not documented in `dot-json`. Either way it would be a breaking change.

---

[![install size](https://packagephobia.com/badge?p=dot-json)](https://packagephobia.com/result?p=dot-json) isn't a huge deal but lighter dependencies are always nice.

**Comment by maikelvl** [comment]
Thanks for submitting this issue. I consider this package in maintenance mode.
