### ISSUE TITLE
is it possible to save array values?

### ISSUE THREAD

**Issue by opensas** [maikelvl/dot-json#16]
I'm trying to save the following value to my package.json file

```json
  "jest": {
    "moduleFileExtensions": [
      "js",
      "ts",
      "svelte"
    ]
  }
```

**Comment by maikelvl** [comment]
It is possible with `dot-json`...

```sh
dot-json package.json jest.moduleFileExtensions.0 js
dot-json package.json jest.moduleFileExtensions.1 ts
dot-json package.json jest.moduleFileExtensions.2 svelte
```

...but may be not the best way.

---

I would recommend [`jq`](https://stedolan.github.io/jq) for this, which is more advanced:

<details>
<summary>jq install</summary>

```sh
brew install jq
# or
apk add jq
# or
apt-get install jq
```

</details>

```sh
tmpfile=$(mktemp -u)
jq '.jest.moduleFileExtensions = ["js", "ts", "svelte"]' package.json > $tmpfile
mv $tmpfile package.json
```

or using `jq` with [`sponge`](https://joeyh.name/code/moreutils/):

<details>
<summary>sponge install</summary>

```sh
brew install moreutils
# or
apk add moreutils
# or
apt-get install moreutils
```

</details>

```sh
jq '.jest.moduleFileExtensions = ["js", "ts", "svelte"]' package.json | sponge package.json
```

Documentation: https://stedolan.github.io/jq/manual/
Playground: https://jqplay.org

**Comment by airtonix** [comment]
to push new primitives : 

```console
$ dot-json package.json jest.moduleFileExtensions. js
$ dot-json package.json jest.moduleFileExtensions. ts
$ dot-json package.json jest.moduleFileExtensions. svelte
```

leave off the aray index

**Comment by fregante** [comment]
I suggest adding a --json-input parameter so that the input can be interpreted as such:

``` sh
dot-json a.json key '[1,2]'
# {"key": "[1,2]"}

dot-json a.json key '[1,2]' --json-input
# {"key": [1,2]}
```

This would be nice because it also enables support for objects

``` sh
dot-json a.json key '{"a":"b"}' --json-input
# {"key": {"a":"b"}}
```

**Comment by maikelvl** [comment]
@fregante Please use [`jq`](https://stedolan.github.io/jq) for advanced use cases.

```sh
jq -n '.key = [1,2]' > a.json
```

```sh
jq -n '.key = {"a":1, "b":2}' > a.json
```

```sh
jq -n '.key = null' > a.json
```

Documentation: https://stedolan.github.io/jq/manual/
Playground: https://jqplay.org/

---

 I'm closing this issue because [`jq`](https://stedolan.github.io/jq) is more suitable for this.

**Comment by fregante** [comment]
> I'm closing this issue because [`jq`](https://stedolan.github.io/jq) is more suitable for this.

No it's not, jq doesn't even allow making changes inplace, your examples don't include the input.

By that logic, dot-json is completely useless and we should all just use jq instead (which is super heavy as not available as a cli on npm/npx)

**Comment by maikelvl** [comment]
@fregante Thank you for your kindliness and offered help. 

> jq doesn't allow making changes inplace, and your examples didn't include the input.

You're correct `jq` doesn't do that by itself. With other tools like [`sponge` you can make it work](https://stackoverflow.com/questions/42716734/modify-a-key-value-in-a-json-using-jq-in-place), (or saving it to a var first) but I get it's not that clean. `jq` is 300kb btw.

I made this small tool for quick edits in package.json, before I knew about `jq`. Therefor this package is not maintained that well, so please know that. However, I'm open to PRs.

How about using https://www.npmjs.com/package/node-jq? That's installable by npm/npx.
