### ISSUE TITLE
Feature request: edit simple .js files too

### ISSUE THREAD

**Issue by binary64** [maikelvl/dot-json#17]
For eslintrc, instead of the usual .eslintrc.json I am using .eslintrc.js which looks like:
```
module.exports = {
  blah: 123,
}
```
Would it be possible to support this file too? `dot-json .eslintrc.js blah 456`

**Comment by maikelvl** [comment]
I can see why you would want that. Unfortunately, to build such feature would require some AST-work and this take a lot of effort.

However, if it fits your use case you could accomplish this with `sed`:

Linux:

```
sed -E 's|(blah:\s+)[^,]+(,?)|\1456\2|g' -i .eslintrc.js
```

macOS:

```
sed -i '' -E 's|(blah: +)[^,]+(,?)|\1456\2|g' .eslintrc.js
```

**Comment by Araxeus** [comment]
or you could use sd - https://github.com/chmln/sd

**Comment by maikelvl** [comment]
I'm closing this as the feature request is not in scope.
