### ISSUE TITLE
String values from CLI converting to numeric in JSON file

### ISSUE THREAD

**Issue by mikecbrant** [maikelvl/dot-json#3]
When doing something like this in CLI:

```
dot-json somefile.json keyname "8080"
```

It results in `keyname` value being numeric `8080` in the JSON representation, which seems as unexpected behavior. 

It would be useful to perhaps have a type specification option or some other way to control serialization behavior.

Thanks for the tool by the way.  I am using it in dockerized node build environments as a means to read/write JSON config files without having to actually invoke any separate JS files for these sorts of use cases.

**Comment by maikelvl** [comment]
Thanks for pointing out your issue. I'm accepting pull requests to add functionality like this.

You could also use the [`jq`](https://stedolan.github.io/jq/download/) tool which has a lot more features for your needs.
To write a numeric value as a string execute the following:

```sh
jq -rM '.keyname |= "8080"' somefile.json | tee somefile.json
```

You can experiment with it on https://jqplay.org/s/HNrNU2qPGb. Hope that helps.
