### ISSUE TITLE
Add support for tab-indented json files

### ISSUE THREAD

**Issue by fregante** [maikelvl/dot-json#6]
`npm` now supports creating/updating tab-indented package.json files. `dot-json` however will just use the `indent` option.

It could use https://github.com/sindresorhus/detect-indent instead of the option.

Currently I have to run this after `dot-json`:

```sh
npx batch-indent -p package.json -f 2-spaces -t tabs
```

**Comment by maikelvl** [comment]
Thanks for the suggestion. I've build it right away. 😅 Could you review it?
