### ISSUE TITLE
Support for dotted keys

### ISSUE THREAD

**Issue by schroedan** [maikelvl/dot-json#8]
Please add support for dotted keys to the binary.

Given the following example:
```json
{
  "foo.bar": "baz"
}
```

...the command:
```bash
$ dot-json example.json foo.bar test
```

...will result in:
```json
{
  "foo.bar": "baz",
  "foo": {
    "bar": "test"
  }
}
```

...instead of:
```json
{
  "foo.bar": "test"
}
```

**Comment by maikelvl** [comment]
Thank you for your suggestion. I've added the usage of dotted keys to the docs.

You can use:
```
dot-json example.json foo..bar test
```

```
{
  "foo.bar": "test"
}
```

**Comment by schroedan** [comment]
Thank you very much. 🚀
